base/urls.py
from django.urls import path
from .views import TaskList,TaskDetail, TaskCreate, TaskUpdate, DeleteView,CustomLoginView,RegisterPage
from django.contrib.auth.views import LogoutView


urlpatterns =[
    path('login/', CustomLoginView.as_view(),name="login"),
    path('logout/', LogoutView.as_view(next_page = 'login'),name="logout"),
    path('register/', RegisterPage.as_view(), name='register'),

    path('', TaskList.as_view(), name="tasks"),
    path('task/<int:pk>/', TaskDetail.as_view(), name='tasks'),
    path('create-task/', TaskCreate.as_view(), name="task-create"),
    path('update-task/<int:pk>/', TaskUpdate.as_view(), name="task-update"),
    path('task-delete/<int:pk>/', DeleteView.as_view(), name="task-delete"),
]

todo_list/urls.py

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
]

base/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Task(models.Model):

    user = models.ForeignKey(User, on_delete= models.CASCADE, null=True,blank=True)
    title = models.CharField(max_length=200)
    description = models.TextField(null=True,blank=True)
    complete = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['complete']

base/views.py
from django.shortcuts import render,redirect
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from django.urls import reverse_lazy

from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login

from .models import Task

class CustomLoginView(LoginView):
    template_name = 'base/login.html'
    fields = '__all__'
    redirect_authenticated_user = True

    def get_success_url(self):
        return reverse_lazy('tasks')

class RegisterPage(FormView):
    template_name = 'base/register.html'
    form_class = UserCreationForm
    redirect_authenticated_user = True
    success_url = reverse_lazy('tasks')

    def form_valid(self, form):
        user = form.save()
        if user is not None:
            login(self.request,user)
        return super(RegisterPage,self).form_valid(form)
    def get(self,*args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect('tasks')
        return super(RegisterPage,self).get(*args,**kwargs)
class TaskList(LoginRequiredMixin,ListView):
    model = Task
    context_object_name = 'tasks'

    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        context['tasks']= context['tasks'].filter(user=self.request.user)
        context['count'] = context['tasks'].filter(complete=False).count()

        search_input = self.request.GET.get('search-area') or ''
        if search_input:
            context['tasks'] = context['tasks'].filter(
                title__startswith=search_input)
        context['search_input'] = search_input
        return context


class TaskDetail(LoginRequiredMixin, DetailView):
    model = Task
    context_object_name = 'task'
    template_name = 'base/task.html'

class TaskCreate(LoginRequiredMixin,CreateView):
    model = Task
    fields = ['title','description', 'complete']
    success_url = reverse_lazy('tasks')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(TaskCreate, self).form_valid(form)

class TaskUpdate(LoginRequiredMixin,UpdateView):
    model = Task
    fields = ['title','description', 'complete']
    success_url = reverse_lazy('tasks')

class DeleteView(LoginRequiredMixin,DeleteView):
    model = Task
    template_name = 'base/task.html'
    success_url = reverse_lazy('tasks')
    template_name = 'base/task_confirm.html'


base/templates/base/login.html
{% extends 'base/main.html' %}

{% block content %}
 <div style="height:100%;width:100%;display:inline-block">
  <div class="splitdiv" id="leftdiv">
      <div id="leftdivcard">
        <h1 style="padding-top:20px;text-align:center">Sign In</h1>
          <form method="POST">
              {% csrf_token %}
              {{form.as_p}}
             <div style="text-align:center">
            <button id="leftbutton" class="ripple2" type="submit" value="login">Login</button>
    </div>
            </form>
      </div>


  </div>
    <div class="splitdiv" id="rightdiv">
      <div id="rightdivcard">
        <h1 style="padding-top:20px;text-align:center;color:white">Register Here if you don't already have an account</h1>
        <p style="color:white;text-align:center">Do you want to manage your tasks more efficiently ? Just Register !</p>
        <div style="text-align:center">
            <button id="rightbutton" class="ripple" onclick="window.location.href={% url 'register' %}">Register</button>
        </div>
      </div>
    </div>

    </div>

{% endblock content %}

base/templates/base/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>TO DO LIST</title>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">
    <style>

        .header-bar{
            display:flex;
            justify-content: space-between;
            color:#FFF;
            padding:10px;
            border-radius: 5px 5px 0 0;
            background-image: linear-gradient(to right, #8e2de2, #4a00e0);
            margin:0,auto;

        }
        .header-bar a{
            color:#FAFAFA;
            text-decoration:none;
        }
        .task-container {
              margin: auto;
              min-width:500px;
              width: 50%;
              box-sizing:border-box;
              border-radius:10px;
              transform: translateY(10%);
          box-shadow: 10px 10px 1px 0px rgba(78, 205, 196, .2);
              padding: 20px;
              background-image: linear-gradient(131.83deg, #FFFAFA 0%,     #FFF7F7 99.21%);
        }

        #go-back{
        background-color: #8e2de2;
          color: white;
          padding: 11px;
          text-align: center;
          text-decoration: none;
          display: inline-block;
          border-radius:5px;

          }


        #login-button {
          position: relative;
          background-color: rgb(230, 34, 77);
          border-radius: 5px;
          box-shadow: rgb(121, 18, 55) 0px 4px 0px 0px;
          padding: 5px;
          background-repeat: no-repeat;
          box-sizing: border-box;
          width: 120px;
          height:40px;
          color: #fff;
          border: none;
          font-size: 15px;
          transition: all .3s ease-in-out;
          z-index: 1;
          overflow: hidden;
        }

        #login-button::before {
          content: "";
          background-color: rgb(248, 50, 93);
          width: 0;
          height: 100%;
          position: absolute;
          top: 0;
          left: 0;
          z-index: -1;
          transition: width 700ms ease-in-out;
          display: inline-block;
        }

        #login-button:hover::before {
          width: 100%;
        }
        .task-wrapper{
            display:flex;
            align-items:center;
            justify-content: space-between;
            padding:20px;
            background-color:#fff;
            border-top:1px solid rgb(226, 226, 226);
        }

        .task-title{
            display:flex;
            color:red;
        }
        .task-title a{
            text-decoration:none;
            color:@4b5156;
            margin-left:10px;
        }

        .task-complete-icon{
            height:20px;
            width:20px;
            background-color:rgb(105,192,105);
            border-radius: 50%;
        }

        #id_complete{
             position: relative;
                top: 0;
                left: 0;
                  height: 25px;
                  width: 25px;
                  background-color: #eee !important;
        }

        .task-incomplete-icon{
            height:20px;
            width:20px;
            background-color:rgb(218,218,218);
            border-radius: 50%;
        }

        .delete-link{
            text-decoration:none;
            font-weight: 900;
            color:#cf4949;
            font-size: 20px;
            line-height:0;
        }


        #search-add-wrapper{
            display:flex;
            align-items:center;
            justify-content: space-between;
        }

        .button{
            border:1px solid #EB796F;
            background-color:#FAFAFA;
            color:#EB796F;
            padding:10px;
            font-size:14px;
            border-radius:5px;
            cursor:pointer;
            text-decoration:none;
        }

        input[type=text],
        input[type=password],
        textarea{
            border: 1px solid #EB796F;
            border-radius:5px;
            padding:5px;
            width:90%
        }

        label{
            padding-top:10px !important;
            display:block;
        }


        h1,
        h2,
        h3,
        h4,
        h5,
        h5{
            font-family:'Raleway', sans-serif;
        }
        a,
        p{
            color:#8e2de4;
        }

        li{
        color:#9942e5;
        }




        @import url('https://fonts.googleapis.com/css?family=Acme|Lobster');

        /* This allows me to have the full width of the page without the initial padding/margin*/
        body, html {
          margin:0;
          padding:0;
          height: 100%;
          width:100%;
          font-family:Acme;
          min-width:700px;
        }
        input[type=text], input[type=password], textarea {
            border: 1px solid #EB796F;
            border-radius: 5px;
            padding: 5px;
            width: -webkit-fill-available;
        }

        .splitdiv{
          height:100%;
          width:50%;
        }

        /* This part contains all the left side of the screen */
        /* ----------------------------------------- */
        #leftdiv{
          float:left;
          background-color:#FAFAFA;
          height:100vh;
          width:50%;
        }

        #leftdivcard{
          margin:0 auto;
          width:75%;
          background-color:white;
          margin-top: 50vh;
          transform: translateY(-50%);
          box-shadow: 10px 10px 1px 0px rgba(78, 205, 196, .2);
          border-radius:10px
        }
         #leftdivcard-tasklist{
          margin:0 auto;
          width:50%;
          background-color:white;
          margin-top: 50vh;
          transform: translateY(-50%);
          box-shadow: 10px 10px 1px 0px rgba(78, 205, 196, .2);
          border-radius:10px
        }

        #leftbutton{
            background-color:#8e2de2;
            border-radius:5px;
            color:#FFF;
            cursor:pointer;
        }
         #leftbutton a{
            color:#FFF;
            text-decoration:none;
        }

        /* ----------------------------------------- */

        /* This part contains all the left side of the screen */
        /* ----------------------------------------- */
        #rightdiv{
          float:right;
          background-image: linear-gradient(to right, #8e2de2, #4a00e0);
          height:100vh;
        }

        #rightdivcard-tasklist{
          margin:0 auto;
          width:40%;
          margin-top: 50vh;

          background-image: linear-gradient(to right, white 33%,  rgba(255,255,255,0) 0%);
          background-position: bottom;
          background-size: 20px 2px;
          background-repeat: repeat-x;
        }

          #rightdivcard{
          margin:0 auto;
          width:40%;
          margin-top: 25vh;

          background-image: linear-gradient(to right, white 33%,  rgba(255,255,255,0) 0%);
          background-position: bottom;
          background-size: 20px 2px;
          background-repeat: repeat-x;
        }


        #rightbutton{
            background-color:#FFFFFF;
            border-radius:5px;
            color:#4ECDC4;
            cursor:pointer;
        }

        #rightbutton a{
            border-radius:5px;
            color:#4ECDC4;
            text-decoration:none;
        }
        #rightbutton a:hover{
            color:#F85376;
            text-decoration:none;
        }

        /* ----------------------------------------- */

        /* Basic styling */
        /* ----------------------------------------- */

        h1{
          font-family:Lobster;
          color:#8e2de2;
        }

        input{
          font-family:Acme;
          font-size:16px;
        }

        input{
          width:85%;
          height:40px;
          padding:10px;
          margin-left:2%;
          margin-right:2%;
          margin-top:10px;
          margin-bottom:10px;
          display:inline-block;
          background-color:#FAFAFA;
          border:none;
        }

        input:focus {
            outline: none !important;
            border:1px solid #4ECDC4;
            box-shadow: 0 0 5px #719ECE;
        }

        button{
          outline: none !important;
          font-family:Lobster;
          margin-bottom:15px;
          border:none;
          font-size:20px;
          padding:8px;
          padding-left:20px;
          padding-right:20px;
        }

        /* ----------------------------------------- */

        .ripple {
          background-position: center;
          transition: background 0.8s;
        }
        .ripple:hover {
          background: #47a7f5 radial-gradient(circle, transparent 1%, #4ECDC4 1%) center/15000%;
        }
        .ripple:active {
          background-color: #4ECDC4;
          background-size: 100%;
          transition: background 0s;
        }

        .ripple2 {
          background-position: center;
          transition: background 0.8s;
        }
        .ripple2:hover {
          background: #47a7f5 radial-gradient(circle, transparent 1%, #FFFFFF 1%) center/15000%;
        }
        .ripple2:active {
          background-color: #FAFAFA;
          background-size: 100%;
          transition: background 0s;
        }
    </style>

    </head>
    <body>
        <div class="container">
            {% block content %}

            {% endblock content %}
        </div>
    </body>
    </html>

base/templates/base/register.html
{% extends 'base/main.html' %}

{% block content %}
 <div style="height:100%;width:100%;display:inline-block">
  <div class="splitdiv" id="leftdiv">
      <div id="leftdivcard">
        <h1 style="padding-top:20px;text-align:center">Register</h1>
          <form method="POST">
              {% csrf_token %}
              {{form.as_p}}
             <div style="text-align:center">
            <button id="leftbutton" class="ripple2" type="submit" value="Register">Login</button>
    </div>
            </form>
      </div>


  </div>
    <div class="splitdiv" id="rightdiv">
      <div id="rightdivcard">
        <h1 style="padding-top:20px;text-align:center;color:white">Came here accidentally ?</h1>
          <h1 style="padding-top:20px;text-align:center;color:white">Already have an account</h1>
        <p style="color:white;text-align:center">Want to go back to the login page ? Just click login button!</p>
        <div style="text-align:center">
            <button id="rightbutton" class="ripple"><a href="{% url 'login' %}">Login</a></button>
        </div>
      </div>
    </div>

    </div>

{% endblock content %}

base/templates/base/task.html
{% extends 'base/main.html' %}

{% block content %}
<div class="task-container">
    <div class="header-bar">
        <h1 style="color:#FFF">Task: {{task}} </h1>
    </div>
    <div class="description">
            <h2>
                Description
            </h2>
        <hr>
        <p>{{task.description}}</p>
    </div>
    <hr>
    <div class="edit">
        <button id="leftbutton" class="ripple2" type="submit" value="login">
            <a href="{% url 'task-update' task.id %}">Edit</a>
        </button>

        <a href="{% url 'tasks' %}" id="go-back">Go back</a>

    </div>
</div>

{% endblock content %}

base/templates/base/task_confirm.html
{% extends 'base/main.html' %}

{% block content %}
<div class="task-container">
    <div class="header-bar">
        <h1 style="color:#FFF">Delete Confirmation page</h1>
    </div>
    <form method="POST">
        {% csrf_token %}
        <h2>Are you sure you want to delete this task?"</h2>
        <h1>Task Title</h1>
        <h1>{{task}}</h1>
        <hr>
        <p>{{task.description}}</p>
        <hr>
        {% if task.complete %}
        <p>Task Status: complete</p>
        {% else %}
        <p style="color:red">Task Status: incomplete</p>
        {% endif %}
        <hr>
        <a id ="go-back" href="{% url 'tasks' %}">Go back</a>
        <button style="margin-left:10px; color:white; background-color:red; border-radius:5px;cursor:pointer;"type="submit" value="delete">Delete</button>
    </form>
</div>


{% endblock content %}

base/templates/base/task_form.html
{% extends 'base/main.html' %}

{% block content %}
<div class="task-container">
    <div class="header-bar">
        <h3>Task form</h3>
       <button id="leftbutton" class="ripple2">
           <a href="{% url 'tasks' %}">Go back</a>
    </button>

    </div>
    <form method="POST" action="">
            {% csrf_token %}
            {{form.as_p}}
           <button id="leftbutton" class="ripple2" type="submit" value="Submit">
          Confirm
           </button>


    </form>

</div>

{% endblock content %}

base/templates/base/task_list.html
{% extends 'base/main.html' %}

{% block content %}
<div class="task-container">
    <div class="header-bar">
    <div>
        <h1 style="color:white">Hello {{request.user|title}}</h1>
        <h3 style="margin:0">You have {{count}} task{{ count|pluralize:"s" }} to attend to </h3>
    </div>
    {% if request.user.is_authenticated %}
        <a href="{% url 'logout' %}" id="go-back" style="background-color:red;height:20px;font-family: nunito, sans-serif;">Logout</a>

    {% else %}
         <a href="{% url 'login' %}">Login</a>
    {%endif%}
</div>
<div id="search-add-wrapper" >
    <button id="leftbutton" class="ripple2" type="submit" onclick="window.location.href={% url 'task-create' %}">
        Add task
    </button>
    <form method="get" style="margin-top:20px; display:flex;">
    <input class="search-area" placeholder="Start typing to search " type="text" name='search-area' value="{{search_input}}">
</form>
</div>



<div class="task-items-wrapper">
    {% for task in tasks %}
    <div class="task-wrapper">
        {% if task.complete %}
            <div class="task-title" style="font-family: nunito, sans-serif;">
                <div class="task-complete-icon"></div>
                <i><s><a href="{% url 'tasks' task.id %}">{{task}}</a></s></i>
            </div>
        <a class="delete-link" href="{% url 'task-delete' task.id %}">&#215;</a>
        {% else %}
            <div class="task-title" style="font-family: nunito, sans-serif;">
                <div class="task-incomplete-icon"></div>
                <a href="{% url 'tasks' task.id %}">{{task}}</a>
                </div>
        <a class="delete-link" href="{% url 'task-delete' task.id %}">&#215;</a>
        {% endif %}

    </div>

    {% empty %}
    <h3>No items In List</h3>
    {% endfor %}

</div>
</div>


{% endblock content %}
